### ISSUE TITLE
The answer for هل احتجز/احتجزت؟ does not match the airtable.

### ISSUE THREAD

**Issue by GrantBaker22** [SocialMediaExchange/muhal#24]
In the Cases of Mustafa Sbeity and Tima Hayek, at least, we have noticed the answer to this question is N/A when the answer is نعم in the airtable. This doesn't seem to be a problem for the English, just the Arabic.

**Comment by kamicut** [comment]
@GrantBaker22 this is because you changed the column name in the airtable (to هل احتجز/ت؟) , and it no longer matches the code at this line https://github.com/SocialMediaExchange/muhal/blob/master/pages/ar/case.js#L79 so the data got out of sync.

If you want different column names, you should do them all at once and let me know what they are so I can change them in the site rendering code. I changed the airtable column name back for now.

**Comment by GrantBaker22** [comment]
Marc, noted and will track these changes in the future. Does this hold true for data validation options as well?

**Comment by kamicut** [comment]
Not sure what you mean by data validation options? Cells are fine to edit in airtable, it's the column names and table names that I need to sync the data.
